#ifndef AKI_VERSION_HPP
#define AKI_VERSION_HPP

#include <kdeversion.h>

const int AKI_MAJOR_VERSION = @AKI_VERSION_MAJOR@;
const int AKI_MINOR_VERSION = @AKI_VERSION_MINOR@;
const int AKI_PATCH_VERSION = @AKI_VERSION_PATCH@;

const char* const AKI_VERSION_STR = "@AKI_VERSION_MAJOR@.@AKI_VERSION_MINOR@.@AKI_VERSION_PATCH@";

#endif // AKI_VERSION_HPP
