#ifndef LIBAKI_EXPORT_HPP
#define LIBAKI_EXPORT_HPP

#include <kdemacros.h>

#ifdef MAKE_LIBAKI_EXPORT
#   define LIBAKI_EXPORT KDE_EXPORT
#else
#   define LIBAKI_EXPORT KDE_IMPORT
#endif // MAKE_LIBAKI_EXPORT

#define AKI_DEPRECATED KDE_DEPRECATED
#define AKI_CONSTRUCTOR_DEPRECATED AKI_CONSTRUCTOR_DEPRECATED

#endif // LIBAKI_EXPORT_HPP
